// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEWQqFiTakaQmla4Uqo2B3UIM8d8bkyLc',
    appId: '1:603861277728:web:e387c70bce6a2ee8887045',
    messagingSenderId: '603861277728',
    projectId: 'gratitude-ffc95',
    authDomain: 'gratitude-ffc95.firebaseapp.com',
    storageBucket: 'gratitude-ffc95.appspot.com',
    measurementId: 'G-CB5G2SDN6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoZE9pxo20GtBu5Ib1ngqfOyGVi4PxFmI',
    appId: '1:603861277728:android:0a76f8bd4a377d9f887045',
    messagingSenderId: '603861277728',
    projectId: 'gratitude-ffc95',
    storageBucket: 'gratitude-ffc95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2S8V77wCEAXaUs9px5NSZU0DPGh5VhUc',
    appId: '1:603861277728:ios:02ab9b1d3148b6c7887045',
    messagingSenderId: '603861277728',
    projectId: 'gratitude-ffc95',
    storageBucket: 'gratitude-ffc95.appspot.com',
    iosBundleId: 'com.example.garttitudeCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2S8V77wCEAXaUs9px5NSZU0DPGh5VhUc',
    appId: '1:603861277728:ios:02ab9b1d3148b6c7887045',
    messagingSenderId: '603861277728',
    projectId: 'gratitude-ffc95',
    storageBucket: 'gratitude-ffc95.appspot.com',
    iosBundleId: 'com.example.garttitudeCoffee',
  );
}
